on:
  push:
    branches:
      - master

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@master@1.8
      with:
        github_token: ${{ secrets.GITHUBTOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
