on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
      - name: download dependencies
        run: make dependencies
      - name: testing
        run: make test
      - name: build linux
        run: make build-linux-amd64
      - name: pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.GITHUB_SHA }}"
          prerelease: true
          title: "Development Build"
          files: |
            commit-*
      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUBTOKEN }}"
          automatic_release_tag: "${{ env.GITHUB_SHA }}"
          prerelease: false
          files: |
            commit-*
